name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-project:
    name: Test Project
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Install gcovr
        if: matrix.os != 'windows'
        uses: threeal/pipx-install-action@v1.0.0
        with:
          packages: gcovr

      - name: Configure Project
        uses: threeal/cmake-action@v2.0.0
        with:
          options: CHECK_COVERAGE_ENABLE_TESTS=ON
          run-build: false

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
        with:
          build-config: debug
          verbose: true
